# Generated by Django 5.0.3 on 2024-05-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'ordering': ('-created_year',)},
        ),
        migrations.RemoveIndex(
            model_name='anime',
            name='anime_app_a_publish_eb5a36_idx',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='published_year',
            new_name='created_year',
        ),
        migrations.AddIndex(
            model_name='anime',
            index=models.Index(fields=['-created_year'], name='anime_app_a_created_4ca083_idx'),
        ),
    ]
