# Generated by Django 5.0.3 on 2024-05-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_alter_anime_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animemedia',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
