# Generated by Django 5.0.3 on 2024-06-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0003_alter_animemedia_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceacting',
            name='anime',
        ),
    ]
