# Generated by Django 5.0.3 on 2024-06-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0005_animemedia_likes_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animemedia',
            name='voice_acting',
        ),
        migrations.DeleteModel(
            name='VoiceActing',
        ),
    ]
