# Generated by Django 5.0.3 on 2024-06-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='value',
        ),
    ]
