# Generated by Django 5.0.3 on 2024-06-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0008_rename_rating_rating_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='user_is_rating',
            field=models.BooleanField(default=False),
        ),
    ]
